# Copyright (C) 2017 Kazumasa Kohtaka <kkohtaka@gmail.com> All right reserved
# This file is available under the MIT license.

ansible_ssh_user: core
ansible_ssh_common_args: -o StrictHostKeyChecking=no
ansible_python_interpreter: /home/core/bin/python

metrics_database: prometheus
