# Copyright (C) 2017 Kazumasa Kohtaka <kkohtaka@gmail.com> All right reserved
# This file is available under the MIT license.

device_name: "{{ block_device | regex_replace('^/', '') | regex_replace('-', '\\x2d') | regex_replace('/', '-') }}"
mount_name: "{{ mount_path | regex_replace('^/', '') | regex_replace('-', '\\x2d') | regex_replace('/', '-') }}"
